# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codec',
            old_name='alias',
            new_name='aliases',
        ),
        migrations.RenameField(
            model_name='codec',
            old_name='language',
            new_name='languages',
        ),
    ]
