# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econv', '0003_auto_20160818_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codec',
            name='aliases',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='codec',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
